name = "w4trc-forms"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[[d1_databases]]
binding = "db"
database_name = "w4trc-forms"
database_id = "bc4598a7-7cd9-4af0-98f5-c0fa1284d748"
